# Generated by Django 4.1.2 on 2022-10-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_ser', models.CharField(max_length=10)),
                ('NAME', models.CharField(max_length=10)),
                ('DESGN', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=10)),
            ],
        ),
    ]
